FROM eclipse-temurin:21-jdk
WORKDIR /app
COPY . .
RUN apt-get update && apt-get install -y ant
RUN ant -f build.xml jar
COPY index.html index.html
COPY Bank-API-Integration_big-1.webp Bank-API-Integration_big-1.webp
EXPOSE 10000
ENV PORT=10000
CMD ["java", "-jar", "dist/banck-api.jar"]